# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-20 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20170120_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='suepervisor',
            new_name='supervisor',
        ),
    ]
