# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-08 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_comisionado', models.CharField(max_length=500)),
                ('identificacion', models.CharField(max_length=500)),
                ('celular', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_de_nacimiento', models.DateField()),
                ('firma', models.ImageField(upload_to='firmas')),
                ('tipo_cuenta', models.CharField(choices=[('Corriente', 'Corriente'), ('Ahorros', 'Ahorros')], max_length=500)),
                ('numero_cuenta', models.CharField(max_length=500)),
                ('banco', models.CharField(max_length=500)),
                ('tipo_vinculacion', models.CharField(choices=[('Planta', 'Planta'), ('Contrato', 'Contrato')], max_length=20)),
                ('numero_contrato', models.CharField(max_length=500)),
                ('objeto_contractual', models.CharField(max_length=5000)),
                ('vencimiento_contrato', models.DateField()),
                ('asignacion_mensual', models.CharField(max_length=500)),
                ('grado', models.CharField(blank=True, max_length=500, null=True)),
                ('supervisor', models.CharField(max_length=500)),
                ('cargo', models.CharField(max_length=500)),
                ('ciudad', models.CharField(max_length=500)),
                ('regional', models.CharField(max_length=500)),
                ('centro', models.CharField(max_length=500)),
                ('ciudad_origen', models.CharField(max_length=500)),
                ('ida_fecha_salida', models.DateField()),
                ('ida_hora_salida', models.TimeField()),
                ('regreso_fecha_partida', models.DateField()),
                ('regreso_hora_partida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional', models.CharField(max_length=500)),
            ],
        ),
    ]
