# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comision.Regional'),
        ),
    ]
