# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-08 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0002_auto_20170608_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='ciudad',
        ),
    ]
