# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-10 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0003_remove_comision_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='firma',
            field=models.FileField(upload_to='firmas'),
        ),
    ]
