# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0004_auto_20170610_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='fecha_de_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
